version: '3.8'

services:
  license-server:
    build: .
    ports:
      - "8088:8080"  
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=changeme
      - DB_USER=changeme
      - DB_PASS=changeme
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - license-network
  db:
    image: postgres:13-alpine  
    environment:
      - POSTGRES_DB=licenses
      - POSTGRES_USER=changeme
      - POSTGRES_PASSWORD=changeme
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    ports:
      - "5438:5432"  
    restart: unless-stopped
    networks:
      - license-network
  redis:
    image: redis:6-alpine  
    command: redis-server --appendonly yes  
    volumes:
      - redis_data:/data
    ports:
      - "6378:6379"  
    restart: unless-stopped
    networks:
      - license-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=changeme@example.com
      - PGADMIN_DEFAULT_PASSWORD=changeme
    ports:
      - "5058:80" 
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - license-network

volumes:
  postgres_data:  
  redis_data:   

networks:
  license-network:  
    driver: bridge